#' Salvador Balkus' ggplot theme
#'
#' This function sets the custom theme of the ggplot.
#'
#' @export

theme_sbalkus_light <- function(){
  axis.title.size = 14
  axis.text.size = 12
  
  
  ggplot2::theme(
    # line = element_line(size=1),
    # rect,
    # text = element_text(family = "abel"),
    # title,
    # aspect.ratio,
    axis.title = element_text(size=axis.title.size),
    axis.title.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0)),
    # axis.title.x.top,
    # axis.title.x.bottom,
    axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0)),
    # axis.title.y.left,
    # axis.title.y.right,
    axis.text = element_text(size=axis.text.size),
    axis.text.x = element_text(margin = margin(t = 5, r = 0, b = 0, l = 0)),
    # axis.text.x.top,
    # axis.text.x.bottom,
    axis.text.y = element_text(margin = margin(t = 0, r = 5, b = 0, l = 0)),
    # axis.text.y.left,
    # axis.text.y.right,
    # axis.ticks,
    # axis.ticks.x,
    # axis.ticks.x.top,
    # axis.ticks.x.bottom,
    # axis.ticks.y,
    # axis.ticks.y.left,
    # axis.ticks.y.right,
    axis.ticks.length = unit(2, "mm"),
    # axis.ticks.length.x,
    # axis.ticks.length.x.top,
    # axis.ticks.length.x.bottom,
    # axis.ticks.length.y,
    # axis.ticks.length.y.left,
    # axis.ticks.length.y.right,
    axis.line = element_line(color="#4d4d4d", size=1),
    # axis.line.x,
    # axis.line.x.top,
    # axis.line.x.bottom,
    # axis.line.y,
    # axis.line.y.left,
    # axis.line.y.right,
    # legend.background = element_rect(),
    legend.margin = margin(t = 15, r = 0, b = 0, l = 0),
    # legend.spacing,
    # legend.spacing.x,
    # legend.spacing.y,
    legend.key = element_rect(fill="white"),
    # legend.key.size,
    # legend.key.height,
    # legend.key.width,
    legend.text = element_text(size=axis.text.size), #margin=margin(t = 0, r = -6*(res / 72) + 8, b = 0, l = -6*(res / 72) + 8)),
    # legend.text.align,
    legend.title = element_text(size=axis.title.size), #margin=margin(t = 0, r = -6*(res / 72) + 8, b = 0, l = -6*(res / 72) + 8)),
    # legend.title.align,
    legend.position = "bottom",
    # legend.direction,
    # legend.justification,
    # legend.box,
    # legend.box.just,
    # legend.box.margin,
    # legend.box.background,
    # legend.box.spacing,
    panel.background = element_rect(fill="white"),
    # panel.border,
    # panel.spacing,
    # panel.spacing.x,
    # panel.spacing.y,
    # panel.grid,
    # panel.grid.major,
    # panel.grid.minor,
    # panel.grid.major.x,
    # panel.grid.major.y,
    # panel.grid.minor.x,
    # panel.grid.minor.y,
    # panel.ontop,
    # plot.background,
    # plot.title,
    # plot.title.position,
    # plot.subtitle,
    # plot.caption,
    # plot.caption.position,
    # plot.tag,
    # plot.tag.position,
    # plot.margin,
    # strip.background,
    # strip.background.x,
    # strip.background.y,
    # strip.placement,
    # strip.text,
    # strip.text.x,
    # strip.text.y,
    # strip.switch.pad.grid,
    # strip.switch.pad.wrap,
    # ...,
    # complete = FALSE,
    # validate = TRUE
  )
}
